name: Build and Publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-frontend:
    name: Build Web Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies with Bun
        working-directory: ./frontend
        run: bun install --frozen-lockfile

      - name: Build frontend with Bun
        working-directory: ./frontend
        run: bun run build

      - name: Upload frontend build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: ./frontend/dist

  build-binary:
    name: Build ${{ matrix.name }} binary
    needs: build-frontend
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: macOS x64
            runner: macos-13
            target: x86_64-apple-darwin
            title: darwin-x64

          - name: macOS ARM
            runner: macos-latest
            target: aarch64-apple-darwin
            title: darwin-arm64

          # - name: Windows x64
          #   runner: windows-latest
          #   target: x86_64-pc-windows-msvc
          #   title: win32-x64

          # - name: Windows ARM
          #   runner: windows-latest
          #   target: aarch64-pc-windows-msvc
          #   title: win32-arm64

          # - name: Linux x64
          #   runner: ubuntu-latest
          #   target: x86_64-unknown-linux-musl
          #   title: linux-x64

          # - name: Linux ARM
          #   runner: ubuntu-latest
          #   target: aarch64-unknown-linux-musl
          #   title: linux-arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download frontend build
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: ./frontend/dist

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          args: "--locked --release"
          target: ${{ matrix.target }}
          strip: true

      - name: Rename binary
        run: |
          mkdir -p target/${{ matrix.target }}/release
          mv target/${{ matrix.target }}/release/runz target/${{ matrix.target }}/release/runz-${{ matrix.title }}-${{ github.ref_name }}

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: runz-${{ matrix.title }}-${{ github.ref_name }}
          path: target/${{ matrix.target }}/release/runz-${{ matrix.title }}-${{ github.ref_name }}

  publish:
    name: Publish to npm
    needs: build-binary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js for npm publish
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"

      - name: Publish with npm
        working-directory: ./npm
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
